hq sandbox - latest/src/objects/Github_Issue__c.object
<CustomObject>
    <fields>
        <fullName>Closed_At__c</fullName>
        <label>Closed At</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <description>Github issues comments.</description>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Created_At__c</fullName>
        <label>Created At</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>GitHub_Milestone__c</fullName>
        <description>GitHub_Milestone</description>
        <label>GitHub Milestone</label>
        <referenceTo>GitHub_Milestones__c</referenceTo>
        <relationshipLabel>Github Issues</relationshipLabel>
        <relationshipName>Github_Issues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Github_URL__c</fullName>
        <label>Github URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Issue_Number__c</fullName>
        <externalId>true</externalId>
        <label>Issue Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Repo_Id__c</fullName>
        <label>Repo Id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Repo_Name__c</fullName>
        <externalId>true</externalId>
        <label>Repo Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reopened</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Updated_At__c</fullName>
        <label>Updated At</label>
        <type>DateTime</type>
    </fields>
    <label>Github Issue</label>
    <nameField>
        <label>Issue Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Github Issues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hq sandbox - latest/src/objects/Github_Issue_Comment__c.object
<CustomObject>
    <description>Object is to maintain the comments related to Github issues.</description>
    <fields>
        <fullName>Comment_Body__c</fullName>
        <description>Comment_Body</description>
        <label>Comment Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FeedItem_Title__c</fullName>
        <label>FeedItem Title</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Github_Issue__c</fullName>
        <description>Github_Issue</description>
        <label>Github Issue</label>
        <referenceTo>Github_Issue__c</referenceTo>
        <relationshipLabel>Github Issue Comments</relationshipLabel>
        <relationshipName>Github_Issue_Comments1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>created_at__c</fullName>
        <description>created_at</description>
        <label>created at</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>updated_at__c</fullName>
        <description>updated_at</description>
        <label>updated at</label>
        <type>DateTime</type>
    </fields>
    <label>Github Issue Comment</label>
    <nameField>
        <displayFormat>Comment -{0000}</displayFormat>
        <label>Github Issue Comment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Github Issue Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

hq sandbox - latest/src/objects/GitHub_Milestones__c.object
<CustomObject>
    <description>GitHub Milestone</description>
    <fields>
        <fullName>Due_On__c</fullName>
        <label>Due On</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Milestone_Id__c</fullName>
        <description>The Id of this milestone in the GitHub repo</description>
        <label>Milestone_Id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Release__c</fullName>
        <label>Release</label>
        <referenceTo>Release__c</referenceTo>
        <relationshipLabel>GitHub Milestones</relationshipLabel>
        <relationshipName>GitHub_Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reopened</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <description>The URL of the Milestone in GitHub</description>
        <label>URL</label>
        <type>Url</type>
    </fields>
    <label>GitHub Milestone</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GitHub Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hq sandbox - latest/src/objects/Release__c.object
<CustomObject>
    <description>A major application update. Can be made up of multiple package versions and sprints.</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hq sandbox - latest/src/classes/GithubIssue.cls
public class GithubIssue {
    
    public String Name;
    public String body;
    public Datetime closed_at;
    public Datetime created_at;
    public Decimal issueNumber;
    public String state;
    public Datetime updated_at;
    public String url;
    public String repoName;
    public Decimal repoId;
    
    public String comments;
    public String githubIssueId;
    
    // Fields for the milestones
    public string milestone_title;
    public Date milestone_due_on;
    public Datetime milestone_created_at;
    public string milestone_state;
    public Decimal milestone_Id;
    public string milestone_Url;
    
    public GithubIssue() {
        comments='';
        
    }
    public GithubIssue(Map<String, Object> m) {
        
        system.debug('inside constructor----');
        this.Name        = (String)  m.get('title');
        this.body        = (String)  m.get('body');
        this.url         = (String)  m.get('html_url');
        this.issueNumber = (Decimal) m.get('number');
        this.state       = (String)  m.get('state');
        this.created_at  = parseDatetime((String) m.get('created_at'));
        this.updated_at  = parseDatetime((String) m.get('updated_at'));
        
        if (m.get('closed_at') != null) {
            this.closed_at = parseDatetime((String) m.get('closed_at'));
        }
        
        this.repoName    = (String) ((Map<String, Object>) m.get('repo')).get('full_name');
        this.repoId      = (Decimal) ((Map<String, Object>) m.get('repo')).get('id');
        
        if(((Map<String, Object>) m.get('comment')) != null)
            this.comments    = (String) ((Map<String, Object>) m.get('comment')).get('body');

        //  Add Milestone details
        this.milestone_title   = (String) ((Map<String, Object>) m.get('milestone')).get('title');
        this.milestone_Id   = (Decimal)((Map<String, Object>) m.get('milestone')).get('id');
        
        if(((Map<String, Object>) m.get('milestone')).get('due_on') !=null)
            this.milestone_due_on   = parseDate((String)((Map<String, Object>) m.get('milestone')).get('due_on'));
        
        this.milestone_created_at   = parseDatetime((String)((Map<String, Object>) m.get('milestone')).get('created_at'));
        this.milestone_state   = (String)((Map<String, Object>) m.get('milestone')).get('state');
        this.milestone_Url   = (String)((Map<String, Object>) m.get('milestone')).get('url');
    }
    
    public static Date parseDate(String dt) {
        Datetime dtm = parseDatetime(dt);
        Date d = dtm.date();
        return d;
    }
    
    public static Datetime parseDatetime(String dt) {
        String s = dt; 
        String str = s.replace('T',' ').replace('Z', '');
        return DateTime.valueOf(str);
    }
    
    public static void processIssue(Map<String, Object> issueMap) {
        GithubIssue issue = new GithubIssue(issueMap);
        // condition to add milestone 
        if (milestoneExists(issue.milestone_Url)){
        	system.debug('inside processIssue if milestone-----');
            updateMilestone(issue);
            
        }
        else{
        	system.debug('inside processIssue else milestone-----');
            createMilestone(issue);
        }

        if (issueExists(issue.issueNumber, issue.repoId)){
            system.debug('inside processIssue if issue-----');
            updateIssue(issue);
        }
        else{
            system.debug('inside processIssue else issue-----');
            createIssue(issue);
        }
    }
    
    
    // code to identify Milestone is exist or not
    
    public static boolean milestoneExists(string githubMilestoneUrl) {
        if (findMilestone(githubMilestoneUrl) != null) {
            return True;
        } else {
            return False;
        }
    } 
    
    public static GitHub_Milestones__c findMilestone(string githubMilestoneUrl ) {
        GitHub_Milestones__c milestone = null;
        List<GitHub_Milestones__c> milestones = [Select g.URL__c, 
                                                        g.State__c, 
                                                        g.Name, 
                                                        g.Milestone_Id__c, 
                                                        g.Id, 
                                                        g.Due_On__c 
                                                 From GitHub_Milestones__c g Where g.URL__c =: githubMilestoneUrl LIMIT 1];
        if(milestones.size() > 0) {
            return milestones.get(0);
        } else {
            return milestone;
        }
    }
    
    
    // code to identify issue is exist or not
    public static boolean issueExists(Decimal issueNumber, Decimal repoId) {
        if (findIssue(issueNumber, repoId) != null) {
            return True;
        } else {
            return False;
        }
    } 
    
    public static Github_Issue__c findIssue(Decimal issueNumber, Decimal repoId) {
        Github_Issue__c issue = null;
        List<Github_Issue__c> issues = [SELECT Id, 
                                               Name, 
                                               Description__c, 
                                               Github_URL__c, 
                                               Issue_Number__c, 
                                               State__c, 
                                               Created_At__c, 
                                               Updated_At__c, 
                                               Closed_At__c, 
                                               Repo_Name__c, 
                                               Repo_Id__c, 
                                               Comments__c
                                         FROM Github_Issue__c 
                                         WHERE Issue_Number__c = :issueNumber AND Repo_Id__c = :repoId LIMIT 1];
        if(issues.size() > 0) {
            return issues.get(0);
        } else {
            return issue;
        }
    }

    //Method to create Milestone
    public static void createMilestone(GithubIssue issue) {
        
        system.debug('inside createMilestone----------');// 
        GitHub_Milestones__c newGitHubMilestones = new GitHub_Milestones__c();
            
            newGitHubMilestones.URL__c           = issue.milestone_Url;
            newGitHubMilestones.Name             = issue.milestone_title;
            newGitHubMilestones.Milestone_Id__c  = issue.milestone_Id;
            newGitHubMilestones.Due_On__c        = issue.milestone_due_on;
            newGitHubMilestones.State__c         = issue.milestone_state;
            
            //newGitHubMilestones.Release__c       = ;
            
        insert newGitHubMilestones;
        
    }

    //Method to create Issue 
    public static void createIssue(GithubIssue issue) {
        system.debug('inside createIssue----------');
        GitHub_Milestones__c m = findMilestone(issue.milestone_Url);
        
        Github_Issue__c newIssue = new Github_Issue__c();
            newIssue.Name               = issue.Name;
            newIssue.Description__c     = issue.body;
            newIssue.Github_URL__c      = issue.url;
            newIssue.Issue_Number__c    = issue.issueNumber;
            newIssue.State__c           = issue.state;
            newIssue.Created_At__c      = issue.created_at;
            newIssue.Updated_At__c      = issue.updated_at;
            newIssue.Closed_At__c       = issue.closed_at;
            newIssue.Repo_Name__c       = issue.repoName;
            newIssue.Repo_Id__c         = issue.repoId;
            newIssue.Comments__c        = issue.comments;
            
            if(m!=null){
                newIssue.GitHub_Milestone__c=m.Id;
            }
        insert newIssue;
        
    }
    
    //Method to Update Milestone
    public static void updateMilestone(GithubIssue issue) {
    	system.debug('inside update Milestone----------');
        GitHub_Milestones__c m = findMilestone(issue.milestone_Url);
            m.URL__c           = issue.milestone_Url;
            m.Name             = issue.milestone_title;
            m.Milestone_Id__c  = issue.milestone_Id;
            m.Due_On__c        = issue.milestone_due_on;
            m.State__c         = issue.milestone_state;
        update m;
        
    }

    //Method to Update Issue 
    public static void updateIssue(GithubIssue issue) {
    	system.debug('inside updateIssue----------');
        GitHub_Milestones__c m = findMilestone(issue.milestone_Url);
        
        system.debug('inside updateIssue------milestone----'+m);
        
        Github_Issue__c i = findIssue(issue.issueNumber, issue.RepoId);
        i.Name            = issue.Name;
        i.Description__c  = issue.body;
        i.Github_URL__c   = issue.url;
        i.Issue_Number__c = issue.issueNumber;
        i.State__c        = issue.state;
        i.Created_At__c   = issue.created_at;
        i.Updated_At__c   = issue.updated_at;
        i.Closed_At__c    = issue.closed_at;
        i.Repo_Name__c    = issue.repoName;
        i.Repo_Id__c      = issue.repoId;
        
        if(issue.comments!='')
            i.Comments__c     = issue.comments;
            
        if(m!=null)
                i.GitHub_Milestone__c=m.Id;
                
        update i;
        
        if(i.Comments__c !='' && i.Comments__c != null){
            Github_Issue_Comment__c issueComment = new Github_Issue_Comment__c();
            issueComment.Github_Issue__c    = i.Id;
            issueComment.Comment_Body__c    = i.Comments__c;
            issueComment.FeedItem_Title__c  = i.Description__c;
            insert issueComment;
            system.debug('===issueComment===='+issueComment);
            
        }
    }
}